/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controlador.CrudAuthorController;

/**
 *
 * @author shurima
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    private RegistroAutorView regAuthorView;
    private RegistroPublisherView regPublisherView;
    private RegistroBookView regBookView;
    private RegistroUserView regUserView;
    private RegistroBorrowView regBorrowView;
    private EntregaBookView entregaLibroView;
    private ListBooksView listBooksView;
    
    public PrincipalView() {
        initComponents();
        regAuthorView = new RegistroAutorView();
        regPublisherView = new RegistroPublisherView();
        regBookView =  new RegistroBookView();
        regUserView = new RegistroUserView();
        regBorrowView = new RegistroBorrowView();
        entregaLibroView = new EntregaBookView();
        listBooksView=new ListBooksView();
        add(regAuthorView);
        add(regPublisherView);
        add(regBookView);
        add(regUserView);
        add(regBorrowView);
        add(entregaLibroView);
        add(listBooksView);
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(false);
        regBookView.setVisible(false);
        regUserView.setVisible(false);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        regAuthor = new javax.swing.JMenuItem();
        regEditorial = new javax.swing.JMenuItem();
        regLibro = new javax.swing.JMenuItem();
        regUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        prestarLibro = new javax.swing.JMenuItem();
        entregaLibro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultPrestamos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Registro");

        regAuthor.setText("Autor");
        regAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regAuthorActionPerformed(evt);
            }
        });
        jMenu1.add(regAuthor);

        regEditorial.setText("Editorial");
        regEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEditorialActionPerformed(evt);
            }
        });
        jMenu1.add(regEditorial);

        regLibro.setText("Libro");
        regLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLibroActionPerformed(evt);
            }
        });
        jMenu1.add(regLibro);

        regUser.setText("Usuario");
        regUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserActionPerformed(evt);
            }
        });
        jMenu1.add(regUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prestamos");

        prestarLibro.setText("Prestar Libro");
        prestarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestarLibroActionPerformed(evt);
            }
        });
        jMenu2.add(prestarLibro);

        entregaLibro.setText("Entrega  de Libro");
        entregaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregaLibroActionPerformed(evt);
            }
        });
        jMenu2.add(entregaLibro);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Consultas");

        consultPrestamos.setText("Consultar Prestamos de Libros por Usuario");
        consultPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultPrestamosActionPerformed(evt);
            }
        });
        jMenu4.add(consultPrestamos);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Salir");

        exit.setText("Salir de la aplicacion");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu3.add(exit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regAuthorActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(true);
        regBookView.setVisible(false);
        regPublisherView.setVisible(false);
        regUserView.setVisible(false);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(false);
    }//GEN-LAST:event_regAuthorActionPerformed

    private void regEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEditorialActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(true);
        regBookView.setVisible(false);
        regUserView.setVisible(false);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(false);
    }//GEN-LAST:event_regEditorialActionPerformed

    private void regLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLibroActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(false);
        regBookView.setVisible(true);
        regUserView.setVisible(false);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(false);
    }//GEN-LAST:event_regLibroActionPerformed

    private void regUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(false);
        regBookView.setVisible(false);
        regUserView.setVisible(true);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(false);
    }//GEN-LAST:event_regUserActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void prestarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestarLibroActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(false);
        regBookView.setVisible(false);
        regUserView.setVisible(false);
        regBorrowView.setVisible(true);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(false);
    }//GEN-LAST:event_prestarLibroActionPerformed

    private void entregaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregaLibroActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(false);
        regBookView.setVisible(false);
        regUserView.setVisible(false);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(true);
        listBooksView.setVisible(false);
    }//GEN-LAST:event_entregaLibroActionPerformed

    private void consultPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultPrestamosActionPerformed
        // TODO add your handling code here:
        regAuthorView.setVisible(false);
        regPublisherView.setVisible(false);
        regBookView.setVisible(false);
        regUserView.setVisible(false);
        regBorrowView.setVisible(false);
        entregaLibroView.setVisible(false);
        listBooksView.setVisible(true);
    }//GEN-LAST:event_consultPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultPrestamos;
    private javax.swing.JMenuItem entregaLibro;
    private javax.swing.JMenuItem exit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem prestarLibro;
    private javax.swing.JMenuItem regAuthor;
    private javax.swing.JMenuItem regEditorial;
    private javax.swing.JMenuItem regLibro;
    private javax.swing.JMenuItem regUser;
    // End of variables declaration//GEN-END:variables
}
